version: "3.9"
services:
  app:
    build: .
    image: "netquest-rails:local"
    command: bundle exec unicorn -c config/unicorn.rb
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
  
  database:
    image: mysql:latest
    volumes:
      - ./.mysql-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "3307:3306"
