version: "3.9"
services:
  app:
    build: .
    image: "netquest-rails:local"
    command: unicorn -c config/unicorn.rb
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8010:8010"
    depends_on:
      - database
  
  database:
    image: mysql:latest
    volumes:
      - ./.mysql-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
